export const ToDoConstants = {
    GET_TO_DO_LIST_REQUEST: 'GET_TO_DO_LIST_REQUEST',
    GET_TO_DO_LIST_SUCCESS: 'GET_TO_DO_LIST_SUCCESS',
    GET_TO_DO_LIST_FALSE: 'GET_TO_DO_LIST_FALSE',

    ADD_TO_DO_LIST_REQUEST: 'ADD_TO_DO_LIST_REQUEST',
    ADD_TO_DO_LIST_SUCCESS: 'ADD_TO_DO_LIST_SUCCESS',
    ADD_TO_DO_LIST_FALSE: 'ADD_TO_DO_LIST_FALSE',

    EDIT_TO_DO_LIST_REQUEST: 'EDIT_TO_DO_LIST_REQUEST',
    EDIT_TO_DO_LIST_SUCCESS: 'EDIT_TO_DO_LIST_SUCCESS',
    EDIT_TO_DO_LIST_FALSE: 'EDIT_TO_DO_LIST_FALSE',

    DELETE_TO_DO_LIST_REQUEST: 'DELETE_TO_DO_LIST_REQUEST',
    DELETE_TO_DO_LIST_SUCCESS: 'DELETE_TO_DO_LIST_SUCCESS',
    DELETE_TO_DO_LIST_FALSE: 'DELETE_TO_DO_LIST_FALSE',

    SEARCH_TO_DO_LIST_REQUEST: 'SEARCH_TO_DO_LIST_REQUEST',
    SEARCH_TO_DO_LIST_SUCCESS: 'SEARCH_TO_DO_LIST_SUCCESS',
    SEARCH_TO_DO_LIST_FALSE: 'SEARCH_TO_DO_LIST_FALSE',
}